name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-tests:
    name: PR Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: tests
        run: |
          npm test 2>&1 | tee test-output.txt
          echo "test_exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Generate coverage
        run: npm run test:coverage
        continue-on-error: true

      - name: Extract test results
        id: test_results
        run: |
          # Extract test counts from output
          PASSED=$(grep -oP '\d+(?= passed)' test-output.txt | head -1 || echo "0")
          FAILED=$(grep -oP '\d+(?= failed)' test-output.txt | head -1 || echo "0")
          TOTAL=$((PASSED + FAILED))
          
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT

      - name: Comment PR with test results
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const passed = '${{ steps.test_results.outputs.passed }}';
            const failed = '${{ steps.test_results.outputs.failed }}';
            const total = '${{ steps.test_results.outputs.total }}';
            const exitCode = '${{ steps.tests.outputs.test_exit_code }}';
            
            const status = exitCode === '0' ? '✅ All tests passed!' : '⚠️ Some tests failed';
            const emoji = exitCode === '0' ? '✅' : '❌';
            
            const body = `## ${emoji} Test Results
            
            **Status**: ${status}
            
            - **Passed**: ${passed}
            - **Failed**: ${failed}
            - **Total**: ${total}
            
            ${failed !== '0' ? '⚠️ Please fix failing tests before merging.' : ''}
            
            <details>
            <summary>View Coverage Report</summary>
            
            Coverage reports are available in the workflow artifacts.
            Download the \`coverage-report\` artifact to view detailed HTML coverage.
            
            </details>
            `;
            
            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.type === 'Bot' && comment.body.includes('Test Results')
            );
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-coverage-report
          path: coverage/
          retention-days: 14

      - name: Fail if tests failed
        if: steps.tests.outputs.test_exit_code != '0'
        run: |
          echo "::error::Tests failed. Please fix the failing tests."
          exit 1

