name: CI Pipeline

on:
  push:
    branches: [ main, master, develop, refactoring, fix/ci-node-version ]
  pull_request:
    branches: [ main, master, develop, refactoring, fix/ci-node-version ]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for linting issues
        run: |
          echo "✅ Linting check placeholder"
          echo "Add 'npm run lint' when you have a linter configured"
          # Uncomment when ready: npm run lint

  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    # This job must run after 'lint'
    needs: lint 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # REMOVED the matrix and the first redundant setup step
      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # <-- Hard-coded to 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # REMOVED the redundant 'npm test' step
      - name: Run tests and generate coverage
        run: npm run test:coverage
        env: # <-- ADDED THIS: Passes secrets to your tests
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        # REMOVED the matrix condition
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        # REMOVED the matrix condition
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Comment PR with coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        # REMOVED the matrix condition
        if: github.event_name == 'pull_request'
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true

  build:
    name: Build Check
    runs-on: ubuntu-latest
    # This job must run after 'lint'
    needs: lint 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          # <-- ADDED THIS: Passes secrets to your build step
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .output/
          retention-days: 7